### ISSUE TITLE
Extend interpolation

### ISSUE THREAD

**Issue by alecandido** [felixhekhorn/LeProHQ#1]
In gluon grids, e.g.:

https://github.com/felixhekhorn/LeProHQ/blob/f5302edc5e725badca6dc8db835564120bb7316c/LeProHQpy/src/LeProHQ/data/cg1/cg1-F2_VV-bulk.dat#L1

interpolation in `log(xi)` extends up to `4.605170185988092`, i.e. `xi = 100.00000000000004`.

This is definitely too little, we need at least `3e4`, better `1e5` for `yadism`.

**Note:** notice that `1e5` is the value already used by the quark (most likely because the gluon coefficient is numerically unstable for large `Q2`)

**Comment by felixhekhorn** [comment]
Not needed for now ... the error was triggered by the wrong theory; maybe later I will extend to `2e3` to allow for FFNS4 at HERA

**Comment by alecandido** [comment]
I guess this is done. For me we can close :)

**Comment by felixhekhorn** [comment]
For now, yes
